/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package minimarket_system_pydev.view;

import minimarket_system_pydev.model.Inventory;
import minimarket_system_pydev.model.Product;
import minimarket_system_pydev.model.InsertItemAction;

import javax.swing.table.DefaultTableModel;




public class InventoryTableUI extends javax.swing.JInternalFrame {

    private Object invmodel;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        insertItmBtn = new javax.swing.JButton();
        removeLstItmBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inventTab = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 51, 62));
        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setToolTipText("");
        setDesktopIcon(getDesktopIcon());
        setPreferredSize(new java.awt.Dimension(1150, 686));

        jPanel1.setBackground(new java.awt.Color(234, 255, 255));

        insertItmBtn.setBackground(new java.awt.Color(102, 102, 255));
        insertItmBtn.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        insertItmBtn.setForeground(new java.awt.Color(255, 255, 255));
        insertItmBtn.setText("Insert Item");
        insertItmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertItmBtnActionPerformed(evt);
            }
        });

        removeLstItmBtn.setBackground(new java.awt.Color(102, 102, 255));
        removeLstItmBtn.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        removeLstItmBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeLstItmBtn.setText("Remove Lastests");
        removeLstItmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLstItmBtnActionPerformed(evt);
            }
        });

        inventTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Code Bar", "Stock", "Price"
            }
        ));
        jScrollPane1.setViewportView(inventTab);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1038, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(insertItmBtn)
                        .addGap(50, 50, 50)
                        .addComponent(removeLstItmBtn)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertItmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeLstItmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeLstItmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeLstItmBtnActionPerformed

    }//GEN-LAST:event_removeLstItmBtnActionPerformed

    private void insertItmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertItmBtnActionPerformed
        InsertItemAction insertItemAction = new InsertItemAction(inventTab);
        insertItemAction.actionPerformed(evt);
        
    }//GEN-LAST:event_insertItmBtnActionPerformed

    
    public void showForm() {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            setVisible(true);
        }
    });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton insertItmBtn;
    private javax.swing.JTable inventTab;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeLstItmBtn;
    // End of variables declaration//GEN-END:variables
}
